function MessageFlow(a){function m(a,b,c,d,e,h){a.rect(b,c,d,e);b=f/2+b;d=g+c;a.text(b,g/2+c,h).attr({"text-anchor":"middle",fill:"#000","font-size":14});return a.path("M "+b+" "+d+" V "+(parseInt(a.height)-c)).attr({stroke:"#aaa"})}var d=a.container;a=a.nodeNames;var b;if("object"===typeof d)b=d;else if("string"===typeof d)b=document.getElementById(d);else return;b.innerHTML="";var g=48,f=80;this.margin=20;this.paper=Raphael(b,parseInt(b.style.width),parseInt(b.style.height));this.nodePathArray=
[];this.messages=[];this.lastMessageYOffset=4*this.margin+g;d=[];if(1==a.length)d.push(this.paper.width/2-f/2);else if(2==a.length)d.push(this.margin),d.push(this.paper.width-f-this.margin);else if(2<a.length){d.push(this.margin);var c=a.length-2,e=this.paper.width-2*this.margin-2*f;if(c*(f+this.margin)+this.margin<e){b=Math.round((e-f*c)/(c+1));for(var e=this.margin,h=0;h<c;h++)e+=f+b,d.push(e)}else b.innerHTML="Message Flow diagram unavailable. Too many column nodes.";d.push(this.paper.width-f-
this.margin)}for(c=0;c<a.length;c++)this.nodePathArray.push(m(this.paper,d[c],this.margin,f,g,a[c]))}
MessageFlow.prototype.addMessageLine=function(a){function m(b,c,d,f,e){this.line=b;this.arrow=c;this.primaryText=d;this.secondaryText=f;this.clicked=!1;this.callback=a.callback;this.callbackData=a.callbackData;this.primaryText.data("message",this);null!=this.primaryText&&(this.primaryText.attr({cursor:"pointer"}),this.primaryText.click(function(a){for(a=0;a<e.length;a++)e[a].clicked=!1,e[a].primaryText.attr({fill:"black"}),e[a].secondaryText.attr({fill:"#666"}),e[a].line.attr({stroke:"black"}),e[a].arrow.attr({stroke:"black"});
this.attr({fill:"blue"});f.attr({fill:"blue"});b.attr({stroke:"blue"});c.attr({stroke:"blue"});"undefined"!==typeof this.data("message").callback&&("undefined"!==typeof this.data("message").callbackData&&null!=this.data("message").callbackData)&&(a=this.data("message").callback,a(this.data("message").callbackData));this.data("message").clicked=!0}),this.primaryText.mouseover(function(){this.attr({fill:"blue"})}),this.primaryText.mouseout(function(){this.data("message").clicked||this.attr({fill:"black"})}))}
if("undefined"!==typeof this.nodePathArray&&!(0>a.from||a.from>this.nodePathArray.length||0>a.to||a.to>this.nodePathArray.length||a.from==a.to)){var d=3*this.margin,b=this.nodePathArray[0].attr("path")[1][1]-this.nodePathArray[0].attr("path")[0][2],g=b-this.messages.length*d;if(g<2*d){g=2*d-g;this.paper.setSize(this.paper.width,this.paper.height+g);/msie/.test(navigator.userAgent.toLowerCase())?this.paper.canvas.parentNode.style.height=parseInt(this.paper.canvas.parentNode.style.height)+g+"px":this.paper.canvas.parentElement.style.height=
parseInt(this.paper.canvas.parentElement.style.height)+g+"px";for(var f=0;f<this.nodePathArray.length;f++){var c=this.nodePathArray[f];c.attr({path:"M "+c.attr("path")[0][1]+","+c.attr("path")[0][2]+" V "+(c.attr("path")[1][1]+g)});b+=g}}var b=this.nodePathArray[a.from-1].attr("path")[0][1],e=this.nodePathArray[a.to-1].attr("path")[0][1],g=this.paper.path("M "+b+", "+this.lastMessageYOffset+" H "+e),f="start",c=8,h=e+" "+this.lastMessageYOffset,k=e+6,l=k+" "+(this.lastMessageYOffset-6),k=k+" "+(this.lastMessageYOffset+
6),n=e+" "+this.lastMessageYOffset;a.from<a.to?(k=e-6,l=k+" "+(this.lastMessageYOffset-6),k=k+" "+(this.lastMessageYOffset+6)):(f="end",c=-8);e=this.paper.path("M "+h+" L"+l+" L"+k+" L"+n).attr("fill","black");h=null;"undefined"!=typeof a.primaryText&&null!=a.primaryText&&(h=this.paper.text(b+c,this.lastMessageYOffset-12,a.primaryText).attr({"text-anchor":f,fill:"#000","font-size":13,"font-style":"bold"}));l=null;"undefined"!=typeof a.secondaryText&&null!=a.secondaryText&&(l=this.paper.text(b+c,this.lastMessageYOffset+
10,a.secondaryText).attr({"text-anchor":f,fill:"#666","font-size":12}));b=new m(g,e,h,l,this.messages);this.messages.push(b);this.lastMessageYOffset+=d;return b}};
