(function(r){function k(){this.messageLines=[];this.activeMessageLine;this.nodes=[];this.container;this.canvas;this.messageSpaceRemaining}function n(){this.lineOffsetX;this.linePath;this.style={lineColor:"#aaa",boxBorderColor:"#000",fontSize:"14",textColor:"#000"}}function g(){this.linePath;this.arrowPath;this.primaryText;this.secondaryText;this.selectableArea;this.callbackFunction;this.lineType="expected";this.timer}var q=Math.PI/180,m={expected:{defaultLine:{lineStyle:"stroke-dasharray",lineColor:"black",
primaryTextColor:"black",secondaryTextColor:"#666"},hover:{lineStyle:"stroke-dasharray",lineColor:"blue",primaryTextColor:"blue",secondaryTextColor:"blue"},active:{lineStyle:"stroke-dasharray",lineColor:"blue",primaryTextColor:"blue",secondaryTextColor:"blue"}},received:{defaultLine:{lineStyle:"stroke",lineColor:"#008B00",primaryTextColor:"#008B00",secondaryTextColor:"#008B00"},hover:{lineStyle:"stroke",lineColor:"#22AD22",primaryTextColor:"#22AD22",secondaryTextColor:"#22AD22"},active:{lineStyle:"stroke",
lineColor:"#33BE33",primaryTextColor:"#33BE33",secondaryTextColor:"#33BE33"}},unexpected:{defaultLine:{lineStyle:"stroke",lineColor:"#D2691E",primaryTextColor:"#D2691E",secondaryTextColor:"#D2691E"},hover:{lineStyle:"stroke",lineColor:"#EE7621",primaryTextColor:"#EE7621",secondaryTextColor:"#EE7621"},active:{lineStyle:"stroke",lineColor:"#EE7621",primaryTextColor:"#EE7621",secondaryTextColor:"#EE7621"}},timeout:{defaultLine:{lineStyle:"stroke-dasharray",lineColor:"#D2691E",primaryTextColor:"#D2691E",
secondaryTextColor:"#D2691E"},hover:{lineStyle:"stroke-dasharray",lineColor:"#EE7621",primaryTextColor:"#EE7621",secondaryTextColor:"#EE7621"},active:{lineStyle:"stroke-dasharray",lineColor:"#EE7621",primaryTextColor:"#EE7621",secondaryTextColor:"#EE7621"}},cancelled:{defaultLine:{lineStyle:"stroke-dasharray",lineColor:"#D2691E",primaryTextColor:"#D2691E",secondaryTextColor:"#D2691E"},hover:{lineStyle:"stroke-dasharray",lineColor:"#EE7621",primaryTextColor:"#EE7621",secondaryTextColor:"#EE7621"},
active:{lineStyle:"stroke-dasharray",lineColor:"#EE7621",primaryTextColor:"#EE7621",secondaryTextColor:"#EE7621"}}},p=[];k.prototype.checkArgumentsAreValid=function(a){var b;if(!a)throw{name:"Invalid argument exception",message:"No MessageFlow construction parameters specified."};if(!a.container)throw{name:"Invalid argument exception",message:"No container specified in MessageFlow construction parameters."};if("string"!==typeof a.container&&"object"!==typeof a.container)throw{name:"Invalid argument exception",
message:"Invalid container type specified in MessageFlow construction parameters. Valid types: String or Object."};if(!a.nodeNames||0==a.nodeNames.length)throw{name:"Invalid argument exception",message:"No nodes specified in MessageFlow construction parameters."};for(b=0;b<a.nodeNames.length;b++)if("string"!==typeof a.nodeNames[b])throw{name:"Invalid argument exception",message:"Node specified in MessageFlow construction parameters is not a string. nodeName index:"+b};};k.prototype.constructDiagram=
function(a){this.checkArgumentsAreValid(a);this.getSvgCanvas(a.container,a.nodeNames);this.messageSpaceRemaining=parseInt(this.container.style.height,10)-68-20;this.constructNodes(a.nodeNames);return this};k.prototype.getSvgCanvas=function(a,b){var c;"object"===typeof a?this.container=a:"string"===typeof a&&(this.container=document.getElementById(a));c=parseInt(this.container.style.width,10);if(c<80*b.length+(20*(b.length-1)+40))throw{name:"Display exception",message:"DOM Container not wide enough to display all specified nodes"};
this.container.innerHTML="";this.canvas=Raphael(this.container,c,parseInt(this.container.style.height,10));this.canvas.customAttributes.lineTransition=function(a,b,c){return{path:[["M",a,b],["H",c]],stroke:m.received.defaultLine.lineColor,fill:"black","stroke-dasharray":"","stroke-width":2}};this.canvas.customAttributes.segment=function(a,b,c,h,f){var g=180<f-h;h=h%360*q;f=f%360*q;return{path:[["M",a,b],["l",c*Math.cos(h),c*Math.sin(h)],["A",c,c,0,+g,1,a+c*Math.cos(f),b+c*Math.sin(f)],["z"]],fill:"#888"}}};
k.prototype.constructNodes=function(a){var b,c=this.getBoxGap(a.length),d=c;for(b=0;b<a.length;b++)this.nodes.push((new n).construct(this.canvas,a[b],d)),d+=c+80};k.prototype.getBoxGap=function(a){return(this.canvas.width-80*a)/(a+1)};k.prototype.stretchCanvasToFitNewMessageLine=function(){var a,b;if(120>this.messageSpaceRemaining){a=120-this.messageSpaceRemaining;this.canvas.setSize(this.canvas.width,this.canvas.height+a);this.container.style.height=parseInt(this.container.style.height,10)+a+"px";
for(b=0;b<this.nodes.length;b++){var c=this.nodes[b].linePath;c.attr({path:"M "+c.attr("path")[0][1]+","+c.attr("path")[0][2]+" V "+(c.attr("path")[1][1]+a)})}this.messageSpaceRemaining+=a-60}else this.messageSpaceRemaining-=60};n.prototype.construct=function(a,b,c){this.lineOffsetX=c+40;this.constructNodeTitleBox(a,c,b);this.constructNodeLine(a);return this};n.prototype.constructNodeTitleBox=function(a,b,c){a.rect(b,20,80,48).attr({stroke:this.style.boxBorderColor});a.text(this.lineOffsetX,44,c).attr({"text-anchor":"middle",
fill:this.style.textColor,"font-size":this.style.fontSize})};n.prototype.constructNodeLine=function(a){this.linePath=a.path("M "+this.lineOffsetX+" 68 V "+(parseInt(a.height,10)-20)).attr({stroke:this.style.lineColor})};g.prototype.checkArgumentsAreValid=function(a,b){if(!a)throw{name:"Invalid argument exception",message:"No message line parameters provided."};if(!a.from||!a.to||!a.primaryText)throw{name:"Invalid argument exception",message:"Insufficient message line parameters provided."};if(0>a.from||
a.from>b||0>a.to||a.to>b||a.from==a.to)throw{name:"Invalid argument exception",message:"Invalid message line range (from <-> to)."};if(a.callback&&"function"!==typeof a.callback)throw{name:"Invalid argument exception",message:"Invalid callback object, must be a function."};if(a.lineType&&"expected"!==a.lineType&&"received"!==a.lineType&&"unexpected"!==a.lineType&&"timeout"!==a.lineType)throw{name:"Invalid argument exception",message:"Invalid argument lineStyle."};};g.prototype.construct=function(a,
b,c,d,e){var l="start",h=8,f=d+6,g;b.lineType&&(this.lineType=b.lineType);c<d?(f=d-6,g=f+" "+(e-6),f=f+" "+(e+6)):(g=f+" "+(e-6),f=f+" "+(e+6),l="end",h=-8);this.arrowPath=a.path("M "+d+" "+e+" L"+g+" L"+f+" z");this.linePath=a.path("M "+c+", "+e+" H "+d);this.primaryText=a.text(c+h,e-12,b.primaryText).attr({"text-anchor":l,"font-size":13,"font-style":"bold"});b.secondaryText&&"string"===typeof b.secondaryText&&(this.secondaryText=a.text(c+h,e+10,b.secondaryText).attr({"text-anchor":l,"font-size":12}));
this.selectableArea=a.rect(Math.min(c,d),e-20,Math.abs(d-c),40).attr({stroke:"black","stroke-opacity":0,fill:"black","fill-opacity":0});this.setDefaultStyle();this.callbackFunction=b.callback;return this};g.prototype.bindMouseEvents=function(a){var b=this;this.selectableArea.attr({cursor:"pointer"});this.selectableArea.click(function(c){a.activeMessageLine&&a.activeMessageLine.setDefaultStyle();b.setActiveStyle();a.activeMessageLine=b;b.callbackFunction&&b.callbackFunction()});this.selectableArea.hover(function(){b!==
a.activeMessageLine&&b.setHoverStyle()},function(){b!==a.activeMessageLine&&b.setDefaultStyle()})};g.prototype.setStyle=function(a){var b={stroke:a.lineColor};"stroke"===a.lineStyle?(this.linePath.attr({"stroke-dasharray":""}),b["stroke-width"]=2):"stroke-dasharray"===a.lineStyle&&(b[a.lineStyle]="--",b["stroke-dashoffset"]=11);this.linePath.attr(b);this.arrowPath.attr({fill:a.lineColor,stroke:a.lineColor});this.primaryText.attr({fill:a.primaryTextColor});this.secondaryText&&this.secondaryText.attr({fill:a.secondaryTextColor})};
g.prototype.setDefaultStyle=function(){this.setStyle(m[this.lineType].defaultLine)};g.prototype.setHoverStyle=function(){this.setStyle(m[this.lineType].hover)};g.prototype.setActiveStyle=function(){this.setStyle(m[this.lineType].active)};r.MessageFlow=function(a){this.id=p.push((new k).constructDiagram(a))-1};MessageFlow.prototype.addMessageLine=function(a){var b=p[this.id],c=new g,d,e,l;c.checkArgumentsAreValid(a);b.stretchCanvasToFitNewMessageLine();d=b.nodes[a.from-1].lineOffsetX;e=b.nodes[a.to-
1].lineOffsetX;l=parseInt(b.canvas.height,10)-20-b.messageSpaceRemaining;c.construct(b.canvas,a,d,e,l);c.bindMouseEvents(b);a.lineStyle&&(b.activeMessageLine=c);return b.messageLines.push(c)-1};MessageFlow.prototype.startMessageTimer=function(a,b){var c=p[this.id],d=c.messageLines[a],e=d.arrowPath.attrs.path[0][1],g=d.arrowPath.attrs.path[0][2],e=d.arrowPath.attrs.path[1][1]<e?e+20:e-20,h=Raphael.animation({"stroke-dashoffset":0},1100);d.linePath.animate(h.repeat(Infinity));d.timer=c.canvas.path();
d.timer.attr({segment:[e,g,10,-90,-89],fill:"#888",stroke:"#888","stroke-width":1});d.timer.animate({segment:[e,g,10,-90,269]},b,"linear",function(){this.hide();d.linePath.stop();d.lineType="timeout";d.setDefaultStyle()})};MessageFlow.prototype.changeMessageState=function(a,b){var c,d,e,g;if(b&&"expected"!==b&&"received"!==b&&"unexpected"!==b&&"timeout"!==b&&"cancelled"!==b)throw{name:"Invalid argument exception",message:"Invalid argument lineStyle."};var h=p[this.id],f=h.messageLines[a];f.timer.stop();
"received"===b&&(d=f.linePath.attrs.path[0][1],e=f.linePath.attrs.path[0][2],g=f.linePath.attrs.path[1][1],c=d+(0<g-d?1:-1),c=h.canvas.path("M "+d+","+e+" H "+c).attr({lineTransition:[d,e,c],stroke:m.received.defaultLine.lineColor,"stroke-dasharray":"",fill:"black"}),c.animate({lineTransition:[d,e,g]},600,"linear",function(){f.lineType=b;f.setDefaultStyle();this.remove()}));f.linePath.stop();window.setTimeout(function(a){return function(){f.timer.animate(a,40,"linear",f.timer.hide)}}({"fill-opacity":0,
"stroke-opacity":0}),60)}})(window);
